# Generated by Django 3.2 on 2022-06-06 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_lng_place_lon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'место', 'verbose_name_plural': 'места'},
        ),
    ]
