# Generated by Django 3.2 on 2022-05-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Элемент  заказа', 'verbose_name_plural': 'Элементы заказа'},
        ),
    ]
