# Generated by Django 3.2 on 2022-05-30 07:22

from django.db import migrations


def add_price_to_orders(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for order_item in OrderItem.objects.all():
        price = order_item.quantity * order_item.product.price
        order_item.price = price
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20220530_0655'),
    ]

    operations = [
        migrations.RunPython(add_price_to_orders),
    ]
