# Generated by Django 3.2 on 2022-05-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20220531_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unprocessed', 'Необработанный'), ('In_procces', 'В работе'), ('Сompleted', 'Завершен')], db_index=True, default='Unprocessed', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
