# Generated by Django 3.2 on 2022-06-01 08:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20220531_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='responsible_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_restaurant', to='foodcartapp.restaurant', verbose_name='Ответственный за готовку ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время звонка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('Online', 'Электронно'), ('Cash', 'Наличность'), ('Unknown', 'Неизвестно')], db_index=True, default='Unknown', max_length=15, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время регистрации заказа'),
        ),
    ]
